import type { Locale, MenuItem } from "./menu-types";

/** Textos: ca/it/pt opcionales. Por defecto ca = es; it = en; pt = es (respaldo si falta una columna). */
const L = (
  es: string,
  en: string,
  fr: string,
  de: string,
  ca: string = es,
  it: string = en,
  pt: string = es,
): Record<Locale, string> => ({ es, en, fr, de, ca, it, pt });

const cat = {
  promos: L("Promociones", "Specials", "Promotions", "Angebote", "Promocions", "Offerte speciali", "Promoções"),
  tapas: L("Tapas", "Tapas", "Tapas", "Tapas", "Tapas", "Tapas", "Tapas"),
  tostas: L("Tostas", "Toasts", "Tartines", "Toasts", "Torrades", "Bruschette", "Tostas"),
  carnes: L("Carnes", "Meats", "Viandes", "Fleisch", "Carns", "Carni", "Carnes"),
  pan: L("Pan y extras", "Bread & extras", "Pain et extras", "Brot & Extras", "Pa i extres", "Pane e extra", "Pão e extras"),
  postres: L("Postres", "Desserts", "Desserts", "Desserts", "Postres", "Dolci", "Sobremesas"),
  cervezas: L("Cervezas", "Beers", "Bières", "Biere", "Cerveses", "Birre", "Cervejas"),
  refrescos: L("Refrescos", "Soft drinks", "Boissons sans alcool", "Erfrischungsgetränke", "Refrescos", "Bevande analcoliche", "Refrigerantes"),
  copas: L("Copas", "Spirits", "Spiritueux", "Spirituosen", "Copes", "Superalcolici", "Copos"),
  cafes: L("Cafés", "Coffee", "Cafés", "Kaffee", "Cafès", "Caffè", "Cafés"),
  blancos: L("Blancos", "White wines", "Vins blancs", "Weißweine", "Blancs", "Vini bianchi", "Vinhos brancos"),
  tintos: L("Tintos", "Red wines", "Vins rouges", "Rotweine", "Vins negres", "Vini rossi", "Vinhos tintos"),
  rosados: L("Rosados", "Rosé wines", "Vins rosés", "Roséweine", "Vins rosats", "Vini rosati", "Vinhos rosados"),
  vermu: L("Vermú", "Vermouth", "Vermouth", "Wermut", "Vermut", "Vermouth", "Vermute"),
  cavas: L("Cavas", "Cava", "Cava", "Cava", "Caves", "Cava", "Cavas"),
};

const ag = (es: string) => L(es, es, es, es, es, es, es);

function dish(
  id: string,
  category: Record<Locale, string>,
  name: Record<Locale, string>,
  description: Record<Locale, string>,
  price: number,
  allergens?: Record<Locale, string>,
  priceText?: Record<Locale, string>,
): MenuItem {
  const m: MenuItem = { id, category, name, description, price };
  if (allergens) m.allergens = allergens;
  if (priceText) m.priceText = priceText;
  return m;
}

/** Carta Taberna El Clavo (abril 2026). Precios según carta impresa; pueden variar en el local. */
export const menuItems: MenuItem[] = [
  dish(
    "promo-almuerzo",
    cat.promos,
    L(
      "Almuerzo (hasta las 12 h)",
      "Lunch menu (until 12:00)",
      "Déjeuner (jusqu’à 12 h)",
      "Mittagessen (bis 12 Uhr)",
      "Dinar (fins a les 12 h)",
      "Pranzo (fino alle 12)",
      "Almoço (até às 12 h)",
    ),
    L(
      "Bocadillo, bebida y café: 6,50 € de lunes a viernes; 7,50 € sábados y domingos. Medio almuerzo: 5,50 € (lun–vie) / 6,50 € (sáb–dom).",
      "Sandwich, drink and coffee: €6.50 Mon–Fri; €7.50 Sat–Sun. Half lunch: €5.50 (Mon–Fri) / €6.50 (Sat–Sun).",
      "Sandwich, boisson et café : 6,50 € lun–ven ; 7,50 € sam–dim. Demi-déjeuner : 5,50 € / 6,50 €.",
      "Brotzeit, Getränk und Kaffee: 6,50 € Mo–Fr; 7,50 € Sa–So. Halbes Menü: 5,50 € / 6,50 €.",
      "Entrepà, beguda i cafè: 6,50 € de dilluns a divendres; 7,50 € caps de setmana. Mig dinar: 5,50 € (dl–dv) / 6,50 € (ds–dg).",
      "Panino, bevanda e caffè: €6,50 lun–ven; €7,50 sab–dom. Mezzo pranzo: €5,50 / €6,50.",
      "Sandes, bebida e café: €6,50 seg–sex; €7,50 sáb–dom. Meio almoço: €5,50 / €6,50.",
    ),
    6.5,
    undefined,
    L("desde 6,50 €", "from €6.50", "à partir de 6,50 €", "ab 6,50 €", "des de 6,50 €", "da €6,50", "desde €6,50"),
  ),
  dish(
    "promo-plato-dia",
    cat.promos,
    L(
      "Plato del día (lunes a jueves)",
      "Daily special (Mon–Thu)",
      "Plat du jour (lun–jeu)",
      "Tagesgericht (Mo–Do)",
      "Plat del dia (dilluns a dijous)",
      "Piatto del giorno (lun–gio)",
      "Prato do dia (seg–qui)",
    ),
    L(
      "Incluye el plato del día y café por 10 €.",
      "Includes the daily dish and coffee for €10.",
      "Plat du jour et café inclus pour 10 €.",
      "Tagesgericht und Kaffee für 10 € inklusive.",
      "Inclou el plat del dia i cafè per 10 €.",
      "Include piatto del giorno e caffè per €10.",
      "Inclui o prato do dia e café por €10.",
    ),
    10,
  ),
  dish(
    "promo-viernes",
    cat.promos,
    L(
      "Todos los viernes: cocido",
      "Every Friday: cocido stew",
      "Tous les vendredis : cocido",
      "Freitags: Cocido",
      "Tots els divendres: puchero",
      "Ogni venerdì: cocido",
      "Todas as sextas: cocido",
    ),
    L(
      "Cocido en temporada — 16 €.",
      "Seasonal stew — €16.",
      "Cocido de saison — 16 €.",
      "Saisonaler Eintopf — 16 €.",
      "Puchero de temporada — 16 €.",
      "Cocido di stagione — €16.",
      "Cocido em época — €16.",
    ),
    16,
  ),
  dish(
    "promo-reservas",
    cat.promos,
    L("Reservas", "Reservations", "Réservations", "Reservierungen", "Reserves", "Prenotazioni", "Reservas"),
    L("Tel. 963 287 041", "Phone 963 287 041", "Tél. 963 287 041", "Tel. 963 287 041", "Tel. 963 287 041", "Tel. 963 287 041", "Tel. 963 287 041"),
    0,
    undefined,
    L("963 287 041", "963 287 041", "963 287 041", "963 287 041", "963 287 041", "963 287 041", "963 287 041"),
  ),

  dish(
    "tap-ajoarriero",
    cat.tapas,
    L("Ajoarriero", "Ajoarriero", "Ajoarriero", "Ajoarriero", "Ajoarriero", "Ajoarriero", "Ajoarriero"),
    L(
      "Clásico de la casa.",
      "House classic.",
      "Classique de la maison.",
      "Hausklassiker.",
      "Clàssic de la casa.",
      "Classico della casa.",
      "Clássico da casa.",
    ),
    8,
    ag("Pescado, huevo, crustáceos"),
  ),
  dish(
    "tap-ensaladilla",
    cat.tapas,
    L("Ensaladilla rusa", "Russian salad", "Macédoine", "Russischer Salat", "Amanida russa", "Insalata russa", "Salada russa"),
    L(
      "Receta de barra.",
      "Bar-style recipe.",
      "Recette de comptoir.",
      "Hausrezept.",
      "Recepta de barra.",
      "Ricetta da banco.",
      "Receita de balcão.",
    ),
    8,
    ag("Pescado, huevo, crustáceos"),
  ),
  dish(
    "tap-titaina",
    cat.tapas,
    L("Titaina del Cabanyal", "Titaina del Cabanyal", "Titaina del Cabanyal", "Titaina del Cabanyal", "Titaina del Cabanyal", "Titaina del Cabanyal", "Titaina do Cabanyal"),
    L(
      "Versión marinera.",
      "Seafaring version.",
      "Version marine.",
      "Maritime Version.",
      "Versió marinera.",
      "Versione marinara.",
      "Versão marinheira.",
    ),
    10,
    ag("Pescado, gluten"),
  ),
  dish(
    "tap-boquerones",
    cat.tapas,
    L(
      "Boquerones en vinagre casero",
      "House-pickled anchovies",
      "Anchois au vinaigre maison",
      "Sardellen in Hausessig",
      "Boquerons en vinagre casolà",
      "Acciughe in aceto di casa",
      "Anchovas em vinagre caseiro",
    ),
    L(
      "Vinagre y aceite de oliva.",
      "Vinegar and olive oil.",
      "Vinaigre et huile d’olive.",
      "Essig und Olivenöl.",
      "Vinagre i oli d’oliva.",
      "Aceto e olio d’oliva.",
      "Vinagre e azeite de oliva.",
    ),
    8,
    ag("Pescado"),
  ),
  dish(
    "tap-mojama",
    cat.tapas,
    L(
      "Mojama de Cádiz con tomate y almendras",
      "Cádiz mojama with tomato and almonds",
      "Mojama de Cadix, tomate et amandes",
      "Mojama mit Tomate und Mandeln",
      "Mojama de Cadis amb tomàquet i ametlles",
      "Mojama di Cadice con pomodoro e mandorle",
      "Mojama de Cádiz com tomate e amêndoas",
    ),
    L(
      "Salazón y picada fina.",
      "Cured fish, fine chop.",
      "Poisson salé, brunoise.",
      "Trockenfisch, fein gehackt.",
      "Salat i picada fina.",
      "Salaison e trito fine.",
      "Salgação e picado fino.",
    ),
    10,
    ag("Pescado, frutos secos"),
  ),
  dish(
    "tap-salpicon",
    cat.tapas,
    L("Salpicón de pulpo", "Octopus salad", "Salpicon de poulpe", "Oktopussalat", "Salpicó de pop", "Insalata di polpo", "Salpicão de polvo"),
    L(
      "Fresco y cítrico.",
      "Fresh and citrusy.",
      "Frais et acidulé.",
      "Frisch und zitrusfrisch.",
      "Fresc i cítric.",
      "Fresco e agrumato.",
      "Fresco e cítrico.",
    ),
    9,
    ag("Moluscos, crustáceos"),
  ),
  dish(
    "tap-esgarraet",
    cat.tapas,
    L("Esgarraet", "Esgarraet", "Esgarraet", "Esgarraet", "Esgarraet", "Esgarraet", "Esgarraet"),
    L(
      "Pimiento y bacalao.",
      "Peppers and cod.",
      "Poivrons et morue.",
      "Paprika und Kabeljau.",
      "Pebrot i bacallà.",
      "Peperoni e baccalà.",
      "Pimento e bacalhau.",
    ),
    9,
    ag("Pescado"),
  ),
  dish(
    "tap-tortilla",
    cat.tapas,
    L("Tortilla de patatas", "Spanish omelette", "Tortilla", "Kartoffeltortilla", "Truita de patates", "Frittata di patate", "Tortilha de batatas"),
    L(
      "Jugosa, cebolla opcional.",
      "Juicy; onion optional.",
      "Baveuse, oignon en option.",
      "Saftig, Zwiebel optional.",
      "Jugosa, ceba opcional.",
      "Saporita, cipolla facoltativa.",
      "Suculenta, cebola opcional.",
    ),
    8,
    ag("Huevo, mostaza"),
  ),
  dish(
    "tap-tomate-melva",
    cat.tapas,
    L(
      "Tomate valenciano, lomos de caballa y encurtidos",
      "Valencian tomato, mackerel fillets and pickles",
      "Tomate valencienne, maquereaux et pickles",
      "Valencianische Tomate, Makrele, Gurken",
      "Tomàquet valencià, lloms de verat i conserves",
      "Pomodoro valenciano, filetti di sgombro e sottaceti",
      "Tomate valenciano, lombos de cavala e conservas",
    ),
    L(
      "Aceite virgen extra.",
      "Extra virgin olive oil.",
      "Huile d’olive vierge extra.",
      "Natives Olivenöl extra.",
      "Oli verge extra.",
      "Olio extravergine.",
      "Azeite virgem extra.",
    ),
    15,
    ag("Pescado, sulfitos"),
  ),
  dish(
    "tap-bravas",
    cat.tapas,
    L("Patatas bravas", "Patatas bravas", "Pommes bravas", "Bravas-Kartoffeln", "Patates braves", "Patate bravas", "Batatas bravas"),
    L(
      "Salsa brava y alioli.",
      "Brava sauce and aioli.",
      "Sauce brava et aïoli.",
      "Brava-Sauce und Alioli.",
      "Salsa brava i allioli.",
      "Salsa brava e aioli.",
      "Molho brava e alioli.",
    ),
    7,
    ag("Gluten, sulfitos"),
  ),
  dish(
    "tap-patatas-pobre",
    cat.tapas,
    L(
      "Patatas a lo pobre (huevo, parmesano y trufa)",
      "Poor man’s potatoes (egg, parmesan, truffle)",
      "Pommes à l’ail, œuf, parmesan, truffe",
      "Arme-Leute-Kartoffeln mit Ei, Parmesan, Trüffel",
      "Patates a la pobre (ou, parmesà i tòfona)",
      "Patate alla povera (uovo, parmigiano, tartufo)",
      "Batatas à pobre (ovo, parmesão e trufa)",
    ),
    L(
      "Con huevo, parmesano y trufa.",
      "With egg, parmesan and truffle.",
      "Œuf, parmesan et truffe.",
      "Mit Ei, Parmesan und Trüffel.",
      "Amb ou, parmesà i tòfona.",
      "Con uovo, parmigiano e tartufo.",
      "Com ovo, parmesão e trufa.",
    ),
    14,
    ag("Huevo, lácteos, sulfitos, gluten"),
  ),
  dish(
    "tap-padron",
    cat.tapas,
    L("Pimientos del padrón", "Padrón peppers", "Piments de Padrón", "Padrón-Paprika", "Pebrots del padró", "Peperoni del Padrón", "Pimentos de Padrón"),
    L(
      "Sal gorda y aceite.",
      "Sea salt and oil.",
      "Gros sel et huile.",
      "Grobsalz und Öl.",
      "Sal grossa i oli.",
      "Sale grosso e olio.",
      "Sal grosso e azeite.",
    ),
    8,
  ),
  dish(
    "tap-oreja",
    cat.tapas,
    L(
      "Oreja adobada a la plancha",
      "Grilled marinated pig’s ear",
      "Oreille de porc marinée grillée",
      "Marinierte Schweineohren vom Grill",
      "Orella adobada a la planxa",
      "Orecchio di maiale marinato alla piastra",
      "Orelha de porco adobada na grelha",
    ),
    L(
      "Adobo casero.",
      "House marinade.",
      "Marinade maison.",
      "Hausmarinade.",
      "Adob casolà.",
      "Marinata della casa.",
      "Marinado caseiro.",
    ),
    7,
    ag("Sulfitos"),
  ),
  dish(
    "tap-gambas",
    cat.tapas,
    L("Gambas al ajillo", "Garlic prawns", "Crevettes à l’ail", "Knoblauch-Garnelen", "Gambes a l’all", "Gamberi all’aglio", "Camarões alhos"),
    L(
      "Aceite caliente y guindilla.",
      "Hot oil and chilli.",
      "Huile chaude et piment.",
      "Heißes Öl und Chili.",
      "Oli calent i bitxo.",
      "Olio caldo e peperoncino.",
      "Óleo quente e malagueta.",
    ),
    10,
    ag("Crustáceos"),
  ),
  dish(
    "tap-morcilla",
    cat.tapas,
    L(
      "Morcilla de Burgos, queso de cabra y cebolla caramelizada",
      "Burgos blood sausage, goat cheese, caramelised onion",
      "Morcilla de Burgos, chèvre, oignon confit",
      "Morcilla mit Ziegenkäse und Zwiebelkonfit",
      "Botifarra negra de Burgos, formatge de cabra i ceba caramel·litzada",
      "Sanguinaccio di Burgos, caprino e cipolla caramellata",
      "Morcela de Burgos, queijo de cabra e cebola caramelizada",
    ),
    L(
      "Contraste dulce–salado.",
      "Sweet–savoury contrast.",
      "Contraste sucré-salé.",
      "Süß-salzer Kontrast.",
      "Contrast dolç–salat.",
      "Contrasto dolce-salato.",
      "Contraste doce–salgado.",
    ),
    10,
    ag("Lácteos, sulfitos, gluten"),
  ),
  dish(
    "tap-brie",
    cat.tapas,
    L(
      "Queso brie frito con confitura de frutos rojos",
      "Fried brie with red berry jam",
      "Brie frit et confiture de fruits rouges",
      "Gebratener Brie mit Beerenkonfitüre",
      "Formatge brie fregit amb confitura de fruits vermells",
      "Brie fritto con confettura di frutti rossi",
      "Queijo brie frito com compota de frutos vermelhos",
    ),
    L(
      "Crujiente por fuera.",
      "Crispy outside.",
      "Croustillant au dehors.",
      "Außen knusprig.",
      "Cruixent per fora.",
      "Croccante fuori.",
      "Crocante por fora.",
    ),
    10,
    ag("Lácteos, gluten"),
  ),
  dish(
    "tap-alcachofa-jamon",
    cat.tapas,
    L(
      "Alcachofa con jamón (3 uds.)",
      "Artichoke with ham (3 pcs.)",
      "Artichaut au jambon (3 p.)",
      "Artischocke mit Schinken (3 Stk.)",
      "Carxofa amb pernil (3 u.)",
      "Carciofo con prosciutto (3 pz.)",
      "Alcachofra com presunto (3 un.)",
    ),
    L(
      "Media ración.",
      "Half portion.",
      "Demi-portion.",
      "Halbe Portion.",
      "Mitja ració.",
      "Mezza porzione.",
      "Meia dose.",
    ),
    10,
    ag("Sulfitos"),
  ),
  dish(
    "tap-alcachofa-foie",
    cat.tapas,
    L(
      "Alcachofas con foie (3 uds.)",
      "Artichokes with foie (3 pcs.)",
      "Artichauts au foie gras (3 p.)",
      "Artischocken mit Foie (3 Stk.)",
      "Carxofes amb foie (3 u.)",
      "Carciofi con foie gras (3 pz.)",
      "Alcachofras com foie (3 un.)",
    ),
    L(
      "Untado caliente.",
      "Seared.",
      "Poêlé.",
      "Angebraten.",
      "Marcat calent.",
      "Scottato.",
      "Selado em quente.",
    ),
    12,
  ),
  dish(
    "tap-alcachofa-chipiron",
    cat.tapas,
    L(
      "Alcachofas con chipirón a la parmesana",
      "Artichokes with baby squid parmesan",
      "Artichauts, chipirons à la parmesan",
      "Artischocken mit Tintenfisch und Parmesan",
      "Carxofes amb xipiró a la parmesana",
      "Carciofi con calamaretto alla parmigiana",
      "Alcachofras com choco à parmesã",
    ),
    L(
      "Gratinado.",
      "Gratin.",
      "Gratiné.",
      "Überbacken.",
      "Gratinat.",
      "Gratinato.",
      "Gratinado.",
    ),
    17,
    ag("Moluscos, lácteos, pescado"),
  ),
  dish(
    "tap-berenjenas",
    cat.tapas,
    L("Berenjenas con miel", "Aubergines with honey", "Aubergines au miel", "Auberginen mit Honig", "Albergínies amb mel", "Melanzane al miele", "Beringelas com mel"),
    L(
      "Rebozado fino.",
      "Light batter.",
      "Panure fine.",
      "Feiner Teig.",
      "Rebostat fi.",
      "Pastella leggera.",
      "Empanado fino.",
    ),
    10,
    ag("Gluten"),
  ),
  dish(
    "tap-sardinas",
    cat.tapas,
    L("Sardinas a la plancha", "Grilled sardines", "Sardines grillées", "Gegrillte Sardinen", "Sardines a la planxa", "Sardine alla griglia", "Sardinhas na grelha"),
    L(
      "Temporada.",
      "In season.",
      "De saison.",
      "Saisonal.",
      "Temporada.",
      "Di stagione.",
      "Época.",
    ),
    10,
    ag("Pescado"),
  ),
  dish(
    "tap-atun",
    cat.tapas,
    L(
      "Filete de atún rojo con tomates cherry salteados",
      "Bluefin tuna with sautéed cherry tomatoes",
      "Thon rouge, tomates cerises sautées",
      "Thunfisch mit Kirschtomaten",
      "Filet de tonyina vermella amb cherrys saltats",
      "Filetto di tonno rosso con pomodorini saltati",
      "Posta de atum vermelho com cherry salteados",
    ),
    L(
      "Ajo y perejil.",
      "Garlic and parsley.",
      "Ail et persil.",
      "Knoblauch und Petersilie.",
      "All i julivert.",
      "Aglio e prezzemolo.",
      "Alho e salsa.",
    ),
    12,
    ag("Pescado"),
  ),
  dish(
    "tap-bacalao-titaina",
    cat.tapas,
    L(
      "Bacalao rebozado con titaina",
      "Fried cod with titaina",
      "Morue panée, titaina",
      "Kabeljau paniert mit Titaina",
      "Bacallà arrebossat amb titaina",
      "Baccalà impanato con titaina",
      "Bacalhau panado com titaina",
    ),
    L(
      "Salsa de pimiento.",
      "Pepper sauce.",
      "Sauce aux poivrons.",
      "Paprikasauce.",
      "Salsa de pebrot.",
      "Salsa ai peperoni.",
      "Molho de pimento.",
    ),
    14,
    ag("Pescado, gluten, huevo"),
  ),
  dish(
    "tap-sepia",
    cat.tapas,
    L("Sepia de playa a la plancha", "Grilled cuttlefish", "Seiche grillée", "Gegrillter Sepia", "Sèpia de platja a la planxa", "Seppia di spiaggia alla griglia", "Choco de praia na grelha"),
    L(
      "Plancha viva.",
      "Hot griddle.",
      "Plancha.",
      "Plancha.",
      "Planxa viva.",
      "Piastra ben calda.",
      "Grelha bem quente.",
    ),
    16,
    ag("Moluscos, pescado"),
  ),
  dish(
    "tap-calamar",
    cat.tapas,
    L(
      "Calamar mediterráneo a la plancha",
      "Mediterranean squid",
      "Calamar méditerranéen",
      "Mittelmeer-Tintenfisch",
      "Calamar mediterrani a la planxa",
      "Calamaro mediterraneo alla griglia",
      "Lula mediterrânica na grelha",
    ),
    L(
      "Tentáculo entero.",
      "Whole tentacle.",
      "Tentacule entier.",
      "Ganzes Tentakel.",
      "Tentacle sencer.",
      "Tentacolo intero.",
      "Tentáculo inteiro.",
    ),
    18,
    ag("Moluscos"),
  ),
  dish(
    "tap-torreznos",
    cat.tapas,
    L("Torreznos", "Crispy pork belly", "Torreznos", "Torreznos", "Torreznos", "Torreznos", "Torresmos"),
    L(
      "Chisporroteo y sal.",
      "Crispy and salty.",
      "Croustillant.",
      "Knusprig.",
      "Cruixent i salat.",
      "Croccante e salato.",
      "Crocante e salgado.",
    ),
    8,
    ag("Sulfitos"),
  ),
  dish(
    "tap-bravas-clavo",
    cat.tapas,
    L(
      "Bravas Clavo (salsa de queso y jamón cebo ibérico)",
      "Bravas Clavo (cheese sauce & ibérico ham)",
      "Bravas Clavo (sauce fromage, jambon ibérique)",
      "Bravas Clavo (Käsesauce, Iberico-Schinken)",
      "Braves Clavo (salsa de formatge i pernil ibèric de cebo)",
      "Bravas Clavo (salsa al formaggio e prosciutto iberico)",
      "Bravas Clavo (molho de queijo e presunto ibérico de bolota)",
    ),
    L(
      "Nuestra versión premium.",
      "Our premium take.",
      "Notre version premium.",
      "Unsere Premium-Variante.",
      "La nostra versió premium.",
      "La nostra versione premium.",
      "A nossa versão premium.",
    ),
    14,
    ag("Lácteos, sulfitos, gluten"),
  ),
  dish(
    "tap-chipirones",
    cat.tapas,
    L("Chipirones a la plancha", "Grilled baby squid", "Chipirons grillés", "Gegrillte Kleintintenfische", "Xipirons a la planxa", "Calamaretti alla griglia", "Chipirões na grelha"),
    L(
      "Plancha al punto.",
      "Seared.",
      "À point.",
      "Medium.",
      "Planxa al punt.",
      "Cotti al punto giusto.",
      "Na grelha no ponto.",
    ),
    12,
    ag("Moluscos"),
  ),
  dish(
    "tap-croq-boletus",
    cat.tapas,
    L(
      "Croquetas de boletus (2 uds.)",
      "Porcini croquettes (2 pcs.)",
      "Croquettes cèpes (2 p.)",
      "Steinpilz-Kroketten (2 Stk.)",
      "Croquetes de rovelló (2 u.)",
      "Crocchette ai porcini (2 pz.)",
      "Croquetes de bolets (2 un.)",
    ),
    L(
      "Cremosas.",
      "Creamy.",
      "Crémeuses.",
      "Cremig.",
      "Cremoses.",
      "Cremose.",
      "Cremosas.",
    ),
    4,
    ag("Lácteos, gluten, huevo"),
  ),
  dish(
    "tap-croq-cecina",
    cat.tapas,
    L(
      "Croquetas de cecina (2 uds.)",
      "Cecina croquettes (2 pcs.)",
      "Croquettes cecina (2 p.)",
      "Cecina-Kroketten (2 Stk.)",
      "Croquetes de cecina (2 u.)",
      "Crocchette di cecina (2 pz.)",
      "Croquetes de cecina (2 un.)",
    ),
    L(
      "Ahumado suave.",
      "Mild smoke.",
      "Fumé doux.",
      "Milder Rauch.",
      "Fumat suau.",
      "Affumicatura delicata.",
      "Fumado suave.",
    ),
    4,
    ag("Lácteos, gluten, huevo, sulfitos"),
  ),
  dish(
    "tap-croq-gamba",
    cat.tapas,
    L(
      "Croquetas de gamba roja (2 uds.)",
      "Red prawn croquettes (2 pcs.)",
      "Croquettes gambas rouges (2 p.)",
      "Rote-Garnele-Kroketten (2 Stk.)",
      "Croquetes de gamba vermella (2 u.)",
      "Crocchette di gambero rosso (2 pz.)",
      "Croquetes de gamba vermelha (2 un.)",
    ),
    L(
      "Sabor marino.",
      "Seafood flavour.",
      "Goût iodé.",
      "Meeresnote.",
      "Sabor marí.",
      "Sapore di mare.",
      "Sabor a mar.",
    ),
    4,
    ag("Lácteos, gluten, huevo, crustáceos, pescado"),
  ),
  dish(
    "tap-croq-jamon",
    cat.tapas,
    L(
      "Croquetas de jamón (2 uds.)",
      "Ham croquettes (2 pcs.)",
      "Croquettes jambon (2 p.)",
      "Schinken-Kroketten (2 Stk.)",
      "Croquetes de pernil (2 u.)",
      "Crocchette al prosciutto (2 pz.)",
      "Croquetes de presunto (2 un.)",
    ),
    L(
      "Curación larga.",
      "Long cure.",
      "Longue affinage.",
      "Lang gereift.",
      "Curació llarga.",
      "Lunga stagionatura.",
      "Cura longa.",
    ),
    4,
    ag("Lácteos, gluten, huevo"),
  ),
  dish(
    "tap-croq-carrillera",
    cat.tapas,
    L(
      "Croquetas de carrillera (2 uds.)",
      "Cheek croquettes (2 pcs.)",
      "Croquettes joue (2 p.)",
      "Backen-Kroketten (2 Stk.)",
      "Croquetes de galta (2 u.)",
      "Crocchette di guancia (2 pz.)",
      "Croquetes de faceira (2 un.)",
    ),
    L(
      "Reducción oscura.",
      "Dark reduction.",
      "Réduction brune.",
      "Dunkle Reduktion.",
      "Reducció fosca.",
      "Riduzione scura.",
      "Redução escura.",
    ),
    4,
    ag("Lácteos, gluten, huevo, sulfitos"),
  ),
  dish(
    "tap-chorizo-sidra",
    cat.tapas,
    L("Chorizos a la sidra", "Chorizo in cider", "Chorizo à la cidre", "Chorizo in Apfelmost", "Xorisos a la sidra", "Chorizo alla sidra", "Chouriços na sidra"),
    L(
      "Sidra natural.",
      "Natural cider.",
      "Cidre nature.",
      "Naturmost.",
      "Sidra natural.",
      "Sidro naturale.",
      "Sidra natural.",
    ),
    7,
    ag("Sulfitos"),
  ),
  dish(
    "tap-tabla-jamon",
    cat.tapas,
    L(
      "Tabla jamón de cebo ibérico y queso curado",
      "Ibérico ham & cured cheese board",
      "Planche jambon ibérique et fromage affiné",
      "Iberico-Schinken mit gereiftem Käse",
      "Taula de pernil ibèric de cebo i formatge curat",
      "Tagliere prosciutto iberico da cebo e formaggio stagionato",
      "Tábua de presunto ibérico de bolota e queijo curado",
    ),
    L(
      "Para compartir.",
      "For sharing.",
      "À partager.",
      "Zum Teilen.",
      "Per compartir.",
      "Da condividere.",
      "Para partilhar.",
    ),
    16,
    ag("Lácteos, sulfitos"),
  ),
  dish(
    "tap-gildas",
    cat.tapas,
    L("Gildas", "Gildas", "Gildas", "Gildas", "Gildes", "Gilda", "Gilda"),
    L(
      "Anchoa, piparra y aceituna.",
      "Anchovy, chilli, olive.",
      "Anchois, piment, olive.",
      "Sardelle, Peperoni, Olive.",
      "Anxova, piparra i oliva.",
      "Acciuga, peperoncino e oliva.",
      "Anchova, piparra e azeitona.",
    ),
    2,
    ag("Pescado, sulfitos"),
  ),
  dish(
    "tap-patatas-bolsa",
    cat.tapas,
    L("Patatas bolsa (chips)", "Bag of crisps", "Chips sachet", "Chips-Tüte", "Patates bossa (xips)", "Patatine in busta", "Batatas pacote (batatas fritas)"),
    L(
      "Clásico de bar.",
      "Bar classic.",
      "Classique de bar.",
      "Klassiker.",
      "Clàssic de bar.",
      "Classico da bar.",
      "Clássico de bar.",
    ),
    1.5,
  ),

  dish(
    "tos-jamon",
    cat.tostas,
    L(
      "Tosta de jamón ibérico con tomate",
      "Ibérico ham & tomato toast",
      "Tartine jambon ibérique, tomate",
      "Iberico-Schinken-Tomaten-Toast",
      "Torrada de pernil ibèric amb tomàquet",
      "Bruschetta prosciutto iberico e pomodoro",
      "Tosta de presunto ibérico com tomate",
    ),
    L(
      "Pan de payés tostado.",
      "Toasted country bread.",
      "Pain paysan grillé.",
      "Landbrot geröstet.",
      "Pa de pagès torrat.",
      "Pane casereccio tostato.",
      "Pão de país tostado.",
    ),
    4,
    ag("Gluten, sulfitos"),
  ),
  dish(
    "tos-sardina",
    cat.tostas,
    L(
      "Tosta de sardina ahumada, tomate y tomate seco",
      "Smoked sardine toast with tomato",
      "Tartine sardine fumée, tomates",
      "Geräucherte Sardelle, Tomaten",
      "Torradeta de sardina fumada, tomàquet i tomàquet sec",
      "Bruschetta sardina affumicata e pomodori",
      "Tosta de sardinha fumada, tomate e tomate seco",
    ),
    L(
      "Capa fina de aceite.",
      "Fine drizzle of oil.",
      "Filet d’huile.",
      "Öl.",
      "Capa fina d’oli.",
      "Filino d’olio.",
      "Fio fino de azeite.",
    ),
    4,
    ag("Gluten, pescado, sulfitos"),
  ),
  dish(
    "tos-salmon",
    cat.tostas,
    L(
      "Tosta de salmón y salsa tártara de la casa",
      "Salmon toast with house tartare sauce",
      "Tartine saumon, sauce tartare",
      "Lachs-Toast mit Tartare",
      "Torradeta de salmó i salsa tàrtara de la casa",
      "Bruschetta salmone e salsa tartara della casa",
      "Tosta de salmão e molho tártaro da casa",
    ),
    L(
      "Eneldo y limón.",
      "Dill and lemon.",
      "Aneth et citron.",
      "Dill und Zitrone.",
      "Anet i llimona.",
      "Aneto e limone.",
      "Endro e limão.",
    ),
    4,
    ag("Gluten, huevo, pescado, sulfitos"),
  ),
  dish(
    "tos-pulled",
    cat.tostas,
    L("Tosta de pulled pork", "Pulled pork toast", "Tartine pulled pork", "Pulled-Pork-Toast", "Torradeta de pulled pork", "Bruschetta pulled pork", "Tosta de pulled pork"),
    L(
      "BBQ suave.",
      "Mild BBQ.",
      "BBQ doux.",
      "Milde BBQ.",
      "BBQ suau.",
      "BBQ delicata.",
      "BBQ suave.",
    ),
    4,
    ag("Gluten, sulfitos, mostaza"),
  ),
  dish(
    "tos-queso-anchoas",
    cat.tostas,
    L(
      "Tosta de crema de queso y anchoas",
      "Cream cheese & anchovy toast",
      "Tartine crème de fromage, anchois",
      "Frischkäse-Sardellen-Toast",
      "Torradeta de crema de formatge i anxoves",
      "Bruschetta crema di formaggio e acciughe",
      "Tosta de creme de queijo e anchovas",
    ),
    L(
      "Textura untuosa.",
      "Creamy texture.",
      "Onctueux.",
      "Cremig.",
      "Textura untuosa.",
      "Texture vellutata.",
      "Textura cremosa.",
    ),
    4,
    ag("Gluten, lácteos, pescado"),
  ),

  dish(
    "car-brocheta",
    cat.carnes,
    L(
      "Brocheta de solomillo de vaca y verduras",
      "Beef sirloin & vegetable skewer",
      "Brochette de faux-filet et légumes",
      "Rinderfiletspieß mit Gemüse",
      "Broqueta de solomillo de vedella i verdures",
      "Spiedino di controfiletto e verdure",
      "Espetada de vazio de novilho e legumes",
    ),
    L(
      "A la brasa.",
      "Charcoal grilled.",
      "Grill.",
      "Vom Grill.",
      "A la brasa.",
      "Alla griglia.",
      "Na brasa.",
    ),
    22,
    ag("Sulfitos, gluten"),
  ),
  dish(
    "car-solomillo",
    cat.carnes,
    L("Solomillo de vaca", "Beef sirloin", "Faux-filet", "Rinderfilet", "Solomillo de vedella", "Controfiletto di manzo", "Vazio de novilho"),
    L(
      "Punto de carne a elegir.",
      "Cooking to taste.",
      "Cuisson au choix.",
      "Garstufe nach Wahl.",
      "Punt de la carn a triar.",
      "Cottura a piacere.",
      "Ponto da carne à escolha.",
    ),
    18,
    ag("Sulfitos, gluten"),
  ),
  dish(
    "car-secreto",
    cat.carnes,
    L(
      "Secreto de cerdo",
      "Iberian pork secret cut",
      "Secret de porc",
      "Iberisches Secreto",
      "Secret ibèric de porc",
      "Taglio secreto iberico",
      "Secreto de porco ibérico",
    ),
    L(
      "Jugoso.",
      "Juicy.",
      "Juteux.",
      "Saftig.",
      "Jugós.",
      "Succoso.",
      "Suculento.",
    ),
    14,
    ag("Sulfitos, gluten"),
  ),
  dish(
    "car-carrillada",
    cat.carnes,
    L(
      "Carrillada al vino",
      "Wine-braised pork cheek",
      "Joue de porc au vin",
      "Schweinebäckchen in Wein",
      "Galta de porc al vi",
      "Guancia di maiale al vino",
      "Faceira de porco ao vinho",
    ),
    L(
      "Lenta reducción.",
      "Slow reduction.",
      "Longue réduction.",
      "Lang geschmort.",
      "Reducció lenta.",
      "Lenta riduzione.",
      "Redução lenta.",
    ),
    15,
    ag("Sulfitos, gluten"),
  ),

  dish(
    "pan-pan",
    cat.pan,
    L("Pan", "Bread", "Pain", "Brot", "Pa", "Pane", "Pão"),
    L(
      "Unidad.",
      "Per piece.",
      "À l’unité.",
      "Stück.",
      "Unitat.",
      "All’unità.",
      "Unidade.",
    ),
    1.2,
    ag("Gluten"),
  ),
  dish(
    "pan-tomate-alioli",
    cat.pan,
    L(
      "Pan con tomate y alioli",
      "Bread with tomato & aioli",
      "Pain tomate et aïoli",
      "Brot mit Tomate und Alioli",
      "Pa amb tomàquet i allioli",
      "Pane con pomodoro e aioli",
      "Pão com tomate e alioli",
    ),
    L(
      "Rallado al momento.",
      "Grated to order.",
      "Râpé à la minute.",
      "Frisch gerieben.",
      "Ratllat al moment.",
      "Grattugiato al momento.",
      "Ralado na hora.",
    ),
    2.5,
    ag("Gluten, huevo"),
  ),

  dish(
    "pos-torrija",
    cat.postres,
    L(
      "Torrija con helado de leche merengada",
      "French toast with meringue-milk ice cream",
      "Pain perdu, glace lait meringué",
      "Arme Ritter mit Baiser-Milcheis",
      "Torrija amb gelat de llet merengada",
      "Pain perdu con gelato al latte meringato",
      "Fatia dourada com gelado de leite merengado",
    ),
    L(
      "Canela y miel.",
      "Cinnamon and honey.",
      "Cannelle et miel.",
      "Zimt und Honig.",
      "Canyella i mel.",
      "Cannella e miele.",
      "Canela e mel.",
    ),
    7,
  ),
  dish(
    "pos-brownie",
    cat.postres,
    L(
      "Brownie con helado de vainilla",
      "Brownie with vanilla ice cream",
      "Brownie, glace vanille",
      "Brownie mit Vanilleeis",
      "Brownie amb gelat de vainilla",
      "Brownie con gelato alla vaniglia",
      "Brownie com gelado de baunilha",
    ),
    L(
      "Chocolate intenso.",
      "Intense chocolate.",
      "Chocolat intense.",
      "Intensive Schokolade.",
      "Xocolata intensa.",
      "Cioccolato intenso.",
      "Chocolate intenso.",
    ),
    7,
  ),
  dish(
    "pos-zanahoria",
    cat.postres,
    L("Tarta de zanahoria", "Carrot cake", "Carrot cake", "Karottenkuchen", "Pastís de pastanaga", "Torta di carote", "Bolo de cenoura"),
    L(
      "Especias y frosting.",
      "Spices and frosting.",
      "Épices et glaçage.",
      "Gewürze und Frosting.",
      "Espècies i cobertura.",
      "Spezie e frosting.",
      "Especiarias e cobertura.",
    ),
    7,
  ),
  dish(
    "pos-queso",
    cat.postres,
    L("Tarta de queso", "Cheesecake", "Cheesecake", "Käsekuchen", "Pastís de formatge", "Cheesecake", "Tarte de queijo"),
    L(
      "Horneada.",
      "Baked.",
      "Cuite au four.",
      "Gebacken.",
      "Al forn.",
      "Al forno.",
      "Assada.",
    ),
    7,
  ),
  dish(
    "pos-turron",
    cat.postres,
    L("Helado de turrón", "Nougat ice cream", "Glace au nougat", "Nouguteis", "Gelat de torró", "Gelato al torrone", "Gelado de torrão"),
    L(
      "Textura cremosa.",
      "Creamy.",
      "Onctueux.",
      "Cremig.",
      "Textura cremosa.",
      "Texture cremosa.",
      "Textura cremosa.",
    ),
    7,
  ),

  dish(
    "cer-cana",
    cat.cervezas,
    L("Caña", "Small beer", "Demi", "Kleines Bier", "Canya", "Birra piccola", "Caneca pequena"),
    L("Barril.", "Draft.", "Pression.", "Vom Fass.", "Barril.", "Spina.", "Barril."),
    1.5,
  ),
  dish(
    "cer-doble",
    cat.cervezas,
    L("Doble", "Large beer", "Pinte", "Großes Bier", "Doble", "Birra grande", "Caneca grande"),
    L("Barril.", "Draft.", "Pression.", "Vom Fass.", "Barril.", "Spina.", "Barril."),
    2.5,
  ),
  dish(
    "cer-alhambra-verde",
    cat.cervezas,
    L("Tercio Alhambra Verde", "Alhambra Verde bottle", "Bouteille Alhambra Verde", "Flasche Alhambra Verde", "Terci Alhambra Verda", "Bottiglia Alhambra Verde", "Garrafa Alhambra Verde"),
    L("33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl."),
    3,
  ),
  dish(
    "cer-00",
    cat.cervezas,
    L(
      "Tercio 0,0 / sin gluten",
      "0.0 / gluten-free bottle",
      "Bouteille 0,0 / sans gluten",
      "Flasche 0,0 / glutenfrei",
      "Terci 0,0 / sense gluten",
      "Bottiglia 0,0 / senza glutine",
      "Garrafa 0,0 / sem glúten",
    ),
    L("33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl."),
    3,
  ),
  dish(
    "cer-tostada",
    cat.cervezas,
    L(
      "Tercio tostada Selecta",
      "Selecta toasted malt bottle",
      "Bouteille Selecta toastée",
      "Flasche Selecta",
      "Terci torrada Selecta",
      "Bottiglia Selecta tostata",
      "Garrafa tostada Selecta",
    ),
    L("33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl."),
    3,
  ),
  dish(
    "cer-clara",
    cat.cervezas,
    L("Clara", "Shandy", "Panaché", "Radler", "Clara", "Radler", "Cerveja com limão"),
    L(
      "Cerveza con limón.",
      "Beer with lemon.",
      "Bière citron.",
      "Bier mit Zitrone.",
      "Cervesa amb llimona.",
      "Birra con limone.",
      "Cerveja com limão.",
    ),
    2.5,
  ),
  dish(
    "cer-radler",
    cat.cervezas,
    L("Radler", "Radler", "Radler", "Radler", "Radler", "Radler", "Radler"),
    L(
      "Refrescante.",
      "Refreshing.",
      "Rafraîchissant.",
      "Erfrischend.",
      "Refrescant.",
      "Dissetante.",
      "Refrescante.",
    ),
    3,
  ),
  dish(
    "cer-magna",
    cat.cervezas,
    L("Tercio Magna", "Magna bottle", "Bouteille Magna", "Flasche Magna", "Terci Magna", "Bottiglia Magna", "Garrafa Magna"),
    L("33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl.", "33 cl."),
    3,
  ),
  dish(
    "cer-pinta",
    cat.cervezas,
    L("Pinta", "Pint", "Pinte", "Pinte", "Pinta", "Pinta", "Pinta"),
    L("Barril.", "Draft.", "Pression.", "Vom Fass.", "Barril.", "Spina.", "Barril."),
    3.5,
  ),
  dish(
    "cer-tinto-verano",
    cat.cervezas,
    L("Tinto de verano", "Wine spritzer", "Sangria blanche", "Sommer-Weinschorle", "Tinto de verano", "Tinto de verano", "Tinto de verão"),
    L(
      "Limón o naranja.",
      "Lemon or orange.",
      "Citron ou orange.",
      "Zitrone oder Orange.",
      "Llimona o taronja.",
      "Limone o arancia.",
      "Limão ou laranja.",
    ),
    4,
  ),
  dish(
    "cer-sangria",
    cat.cervezas,
    L("Sangría", "Sangria", "Sangria", "Sangria", "Sangria", "Sangria", "Sangria"),
    L(
      "Fruta fresca.",
      "Fresh fruit.",
      "Fruits frais.",
      "Frisches Obst.",
      "Fruita fresca.",
      "Frutta fresca.",
      "Fruta fresca.",
    ),
    6,
  ),

  dish(
    "ref-refresco",
    cat.refrescos,
    L("Refrescos", "Soft drinks", "Sodas", "Limonaden", "Refrescos", "Bevande analcoliche", "Refrigerantes"),
    L(
      "Marca del día.",
      "Brand of the day.",
      "Marque du jour.",
      "Marke des Tages.",
      "Marca del dia.",
      "Marca del giorno.",
      "Marca do dia.",
    ),
    2.5,
  ),
  dish(
    "ref-agua",
    cat.refrescos,
    L(
      "Agua 50 cl / con gas",
      "Still or sparkling water",
      "Eau plate ou gazeuse",
      "Still- oder Sprudelwasser",
      "Aigua 50 cl / amb gas",
      "Acqua 50 cl / frizzante",
      "Água 50 cl / com gás",
    ),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    2,
  ),
  dish(
    "ref-aquarius",
    cat.refrescos,
    L(
      "Aquarius naranja / melocotón",
      "Aquarius orange / peach",
      "Aquarius orange / pêche",
      "Aquarius Orange / Pfirsich",
      "Aquarius taronja / préssec",
      "Aquarius arancia / pesca",
      "Aquarius laranja / pêssego",
    ),
    L("50 cl.", "50 cl.", "50 cl.", "50 cl.", "50 cl.", "50 cl.", "50 cl."),
    2.5,
  ),
  dish(
    "ref-zumo",
    cat.refrescos,
    L("Zumos", "Juices", "Jus", "Säfte", "Sucs", "Succhi", "Sumos"),
    L(
      "Naranja o multifruta.",
      "Orange or multivitamin.",
      "Orange ou multifruit.",
      "Orange oder Multivitamin.",
      "Taronja o multifruita.",
      "Arancia o multivitaminico.",
      "Laranja ou multifrutas.",
    ),
    2.5,
  ),
  dish(
    "ref-kas",
    cat.refrescos,
    L("Bitter Kas", "Bitter Kas", "Bitter Kas", "Bitter Kas", "Bitter Kas", "Bitter Kas", "Bitter Kas"),
    L(
      "Clásico valenciano.",
      "Valencian classic.",
      "Classique valencien.",
      "Valencianischer Klassiker.",
      "Clàssic valencià.",
      "Classico valenciano.",
      "Clássico valenciano.",
    ),
    2.5,
  ),

  dish(
    "cop-combinado",
    cat.copas,
    L("Combinados", "Mixed drinks", "Cocktails simples", "Longdrinks", "Combinats", "Combinati", "Combinados"),
    L(
      "Ginebra, ron, whisky…",
      "Gin, rum, whisky…",
      "Gin, rhum, whisky…",
      "Gin, Rum, Whisky…",
      "Ginebra, rom, whisky…",
      "Gin, rum, whisky…",
      "Gin, rum, whisky…",
    ),
    8,
    undefined,
    L("8 / 9 €", "€8 / €9", "8 / 9 €", "8 / 9 €", "8 / 9 €", "8 / 9 €", "8 / 9 €"),
  ),
  dish(
    "cop-combinado-prem",
    cat.copas,
    L("Combinados premium", "Premium mixed drinks", "Cocktails premium", "Premium-Longdrinks", "Combinats premium", "Combinati premium", "Combinados premium"),
    L(
      "Marcas seleccionadas.",
      "Selected brands.",
      "Marques sélectionnées.",
      "Ausgewählte Marken.",
      "Marques seleccionades.",
      "Marchi selezionati.",
      "Marcas selecionadas.",
    ),
    10,
  ),
  dish(
    "cop-vaquerito",
    cat.copas,
    L("Vaquerito", "Vaquerito shot", "Vaquerito", "Vaquerito", "Vaquerito", "Vaquerito", "Vaquerito"),
    L(
      "Shot cremoso.",
      "Creamy shot.",
      "Shot crémeux.",
      "Cremiger Shot.",
      "Shot cremós.",
      "Shot cremoso.",
      "Shot cremoso.",
    ),
    3.5,
  ),
  dish(
    "cop-chupito",
    cat.copas,
    L("Chupito", "Shot", "Shot", "Schnaps", "Chupito", "Chupito", "Chupito"),
    L(
      "Según destilado.",
      "By spirit.",
      "Selon spiritueux.",
      "Je nach Sorte.",
      "Segons destil·lat.",
      "A seconda del distillato.",
      "Conforme o destilado.",
    ),
    2.5,
    undefined,
    L("2,50 / 3 €", "€2.50 / €3", "2,50 / 3 €", "2,50 / 3 €", "2,50 / 3 €", "2,50 / 3 €", "2,50 / 3 €"),
  ),
  dish(
    "cop-copa-prem",
    cat.copas,
    L("Copa premium", "Premium glass", "Verre premium", "Premium-Glas", "Copa premium", "Calice premium", "Copo premium"),
    L(
      "Destilado alto.",
      "Top-shelf spirit.",
      "Spiritueux haut de gamme.",
      "Premium-Spirituose.",
      "Destil·lat d’alta gamma.",
      "Distillato premium.",
      "Destilado premium.",
    ),
    10,
  ),
  dish(
    "cop-copita",
    cat.copas,
    L("Copita", "Small glass", "Petit verre", "Kleines Glas", "Copeta", "Coppetta", "Copinho"),
    L(
      "Licor o mistela.",
      "Liqueur or mistela.",
      "Liqueur ou mistelle.",
      "Likör oder Mistela.",
      "Licor o mistela.",
      "Liquore o mistela.",
      "Licor ou mistela.",
    ),
    4.5,
  ),

  dish(
    "caf-solo",
    cat.cafes,
    L("Café solo", "Espresso", "Café serré", "Espresso", "Cafè sol", "Caffè espresso", "Café simples"),
    L(
      "Intenso.",
      "Strong.",
      "Serré.",
      "Kräftig.",
      "Intens.",
      "Intenso.",
      "Intenso.",
    ),
    1.2,
  ),
  dish(
    "caf-cortado",
    cat.cafes,
    L("Cortado", "Macchiato", "Noisette", "Espresso mit Milch", "Tallat", "Caffè macchiato", "Café pingado"),
    L(
      "Leche templada.",
      "Warm milk.",
      "Lait tiède.",
      "Warmer Milch.",
      "Llet tèbia.",
      "Latte tiepido.",
      "Leite morno.",
    ),
    1.5,
  ),
  dish(
    "caf-leche",
    cat.cafes,
    L("Café con leche", "Coffee with milk", "Café crème", "Milchkaffee", "Cafè amb llet", "Caffè latte", "Café com leite"),
    L(
      "Desayuno.",
      "Breakfast style.",
      "Petit-déjeuner.",
      "Frühstück.",
      "Esmorzar.",
      "Colazione.",
      "Pequeno-almoço.",
    ),
    2,
  ),
  dish(
    "caf-carajillo",
    cat.cafes,
    L("Carajillo", "Coffee with brandy", "Café flambé", "Kaffee mit Brandy", "Carajillo", "Caffè corretto", "Café com bagaço"),
    L(
      "Licor a elegir.",
      "Spirit of your choice.",
      "Alcool au choix.",
      "Likör nach Wahl.",
      "Licor a triar.",
      "Liquore a scelta.",
      "Licor à escolha.",
    ),
    2.5,
  ),
  dish(
    "caf-bombon",
    cat.cafes,
    L("Bombón", "Condensed-milk coffee", "Café bombón", "Bonbon-Kaffee", "Bombó", "Caffè bombón", "Café bombom"),
    L(
      "Leche condensada.",
      "Condensed milk.",
      "Lait concentré sucré.",
      "Kondensmilch.",
      "Llet condensada.",
      "Latte condensato.",
      "Leite condensado.",
    ),
    1.8,
  ),
  dish(
    "caf-americano",
    cat.cafes,
    L("Americano", "Americano", "Americano", "Americano", "Americano", "Americano", "Americano"),
    L(
      "Largo suave.",
      "Mild long black.",
      "Allongé doux.",
      "Milder Long Black.",
      "Llarg suau.",
      "Lungo delicato.",
      "Longo suave.",
    ),
    1.5,
  ),
  dish(
    "caf-cremaet",
    cat.cafes,
    L("Cremaet", "Cremaet (coffee cocktail)", "Cremaet", "Cremaet", "Cremaet", "Cremaet", "Cremaet"),
    L(
      "Tradicional valenciana.",
      "Valencian classic.",
      "Classique valencienne.",
      "Valencianisch.",
      "Tradicional valenciana.",
      "Classico valenciano.",
      "Tradicional valenciana.",
    ),
    3,
  ),
  dish(
    "caf-infusion",
    cat.cafes,
    L("Infusión", "Herbal tea", "Infusion", "Kräutertee", "Infusió", "Tisana", "Infusão"),
    L(
      "Variedad.",
      "Assorted.",
      "Assortiment.",
      "Auswahl.",
      "Varietat.",
      "Assortimento.",
      "Variedade.",
    ),
    2,
  ),

  dish(
    "vin-bl-academia",
    cat.blancos,
    L(
      "Academia de los Nocturnos (Valencia)",
      "Academia de los Nocturnos (Valencia)",
      "Academia de los Nocturnos",
      "Academia de los Nocturnos",
      "Academia dels Nocturns (València)",
      "Academia de los Nocturnos (Valencia)",
      "Academia dos Nocturnos (Valência)",
    ),
    L(
      "Copa / botella.",
      "Glass / bottle.",
      "Verre / bouteille.",
      "Glas / Flasche.",
      "Copa / ampolla.",
      "Calice / bottiglia.",
      "Copo / garrafa.",
    ),
    3,
    undefined,
    L("3 / 16 €", "€3 / €16", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €"),
  ),
  dish(
    "vin-bl-verdeo",
    cat.blancos,
    L("Verdeo", "Verdeo", "Verdeo", "Verdeo", "Verdeo", "Verdeo", "Verdeo"),
    L("Verdejo.", "Verdejo.", "Verdejo.", "Verdejo.", "Verdejo.", "Verdejo.", "Verdejo."),
    3,
    undefined,
    L("3 / 16 €", "€3 / €16", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €"),
  ),
  dish(
    "vin-bl-ramon-b",
    cat.blancos,
    L("Ramón Bilbao (verdejo)", "Ramón Bilbao (Verdejo)", "Ramón Bilbao", "Ramón Bilbao", "Ramón Bilbao (verdejo)", "Ramón Bilbao (Verdejo)", "Ramón Bilbao (verdejo)"),
    L("Rueda.", "Rueda.", "Rueda.", "Rueda.", "Rueda.", "Rueda.", "Rueda."),
    4,
    undefined,
    L("4 / 18 €", "€4 / €18", "4 / 18 €", "4 / 18 €", "4 / 18 €", "4 / 18 €", "4 / 18 €"),
  ),
  dish(
    "vin-bl-pazo",
    cat.blancos,
    L("Pazo de Bruixas (albariño)", "Pazo de Bruixas (Albariño)", "Pazo de Bruixas", "Pazo de Bruixas", "Pazo de Bruixas (albariño)", "Pazo de Bruixas (Albariño)", "Pazo de Bruixas (alvarinho)"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    21,
  ),
  dish(
    "vin-bl-mar-frades",
    cat.blancos,
    L("Mar de Frades (albariño)", "Mar de Frades (Albariño)", "Mar de Frades", "Mar de Frades", "Mar de Frades (albariño)", "Mar de Frades (Albariño)", "Mar de Frades (alvarinho)"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    28,
  ),
  dish(
    "vin-bl-poda",
    cat.blancos,
    L("La Poda (godello)", "La Poda (Godello)", "La Poda", "La Poda", "La Poda (godello)", "La Poda (Godello)", "La Poda (godello)"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    21,
  ),
  dish(
    "vin-bl-iconos",
    cat.blancos,
    L("Iconos (chardonnay)", "Iconos (Chardonnay)", "Iconos", "Iconos", "Iconos (chardonnay)", "Iconos (Chardonnay)", "Iconos (chardonnay)"),
    L(
      "Copa / botella.",
      "Glass / bottle.",
      "Verre / bouteille.",
      "Glas / Flasche.",
      "Copa / ampolla.",
      "Calice / bottiglia.",
      "Copo / garrafa.",
    ),
    3.5,
    undefined,
    L("3,50 / 17 €", "€3.50 / €17", "3,50 / 17 €", "3,50 / 17 €", "3,50 / 17 €", "3,50 / 17 €", "3,50 / 17 €"),
  ),

  dish(
    "vin-ti-academia",
    cat.tintos,
    L(
      "Academia de los Nocturnos (Valencia)",
      "Academia de los Nocturnos (Valencia)",
      "Academia de los Nocturnos",
      "Academia de los Nocturnos",
      "Academia dels Nocturns (València)",
      "Academia de los Nocturnos (Valencia)",
      "Academia dos Nocturnos (Valência)",
    ),
    L("Tinto.", "Red.", "Rouge.", "Rot.", "Negre.", "Rosso.", "Tinto."),
    3,
    undefined,
    L("3 / 16 €", "€3 / €16", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €", "3 / 16 €"),
  ),
  dish(
    "vin-ti-avaniel",
    cat.tintos,
    L("Avaniel (Ribera del Duero)", "Avaniel (Ribera del Duero)", "Avaniel", "Avaniel", "Avaniel (Ribera del Duero)", "Avaniel (Ribera del Duero)", "Avaniel (Ribera del Douro)"),
    L("Joven.", "Young.", "Jeune.", "Jung.", "Jove.", "Giovane.", "Jovem."),
    3.5,
    undefined,
    L("3,50 / 18 €", "€3.50 / €18", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €"),
  ),
  dish(
    "vin-ti-celeste",
    cat.tintos,
    L("Celeste (Ribera del Duero)", "Celeste (Ribera del Duero)", "Celeste", "Celeste", "Celeste (Ribera del Duero)", "Celeste (Ribera del Duero)", "Celeste (Ribera del Douro)"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    20,
  ),
  dish(
    "vin-ti-altos",
    cat.tintos,
    L("Altos Ibéricos (Rioja)", "Altos Ibéricos (Rioja)", "Altos Ibéricos", "Altos Ibéricos", "Altos Ibèrics (Rioja)", "Altos Ibéricos (Rioja)", "Altos Ibéricos (Rioja)"),
    L("Crianza.", "Crianza.", "Crianza.", "Crianza.", "Criança.", "Crianza.", "Crianza."),
    3.5,
    undefined,
    L("3,50 / 18 €", "€3.50 / €18", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €", "3,50 / 18 €"),
  ),
  dish(
    "vin-ti-rb-crianza",
    cat.tintos,
    L("Ramón Bilbao (Rioja)", "Ramón Bilbao (Rioja)", "Ramón Bilbao", "Ramón Bilbao", "Ramón Bilbao (Rioja)", "Ramón Bilbao (Rioja)", "Ramón Bilbao (Rioja)"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    24,
  ),
  dish(
    "vin-ti-rb-reserva",
    cat.tintos,
    L(
      "Ramón Bilbao reserva 2019",
      "Ramón Bilbao Reserva 2019",
      "Ramón Bilbao reserva 2019",
      "Ramón Bilbao Reserva 2019",
      "Ramón Bilbao reserva 2019",
      "Ramón Bilbao Riserva 2019",
      "Ramón Bilbao reserva 2019",
    ),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    28,
  ),
  dish(
    "vin-ti-pittacum",
    cat.tintos,
    L("Petit Pittacum (Bierzo)", "Petit Pittacum (Bierzo)", "Petit Pittacum", "Petit Pittacum", "Petit Pittacum (Bierzo)", "Petit Pittacum (Bierzo)", "Petit Pittacum (Bierzo)"),
    L("Mencía.", "Mencía.", "Mencía.", "Mencía.", "Mencía.", "Mencía.", "Mencía."),
    4,
    undefined,
    L("4 / 20 €", "€4 / €20", "4 / 20 €", "4 / 20 €", "4 / 20 €", "4 / 20 €", "4 / 20 €"),
  ),
  dish(
    "vin-ti-sangre",
    cat.tintos,
    L("Sangre de Toro", "Sangre de Toro", "Sangre de Toro", "Sangre de Toro", "Sangre de Toro", "Sangre de Toro", "Sangre de Toro"),
    L(
      "Botella.",
      "Bottle.",
      "Bouteille.",
      "Flasche.",
      "Ampolla.",
      "Bottiglia.",
      "Garrafa.",
    ),
    15,
  ),

  dish(
    "vin-ro-ramon",
    cat.rosados,
    L(
      "Ramón Bilbao (Rioja)",
      "Ramón Bilbao rosé (Rioja)",
      "Ramón Bilbao rosé",
      "Ramón Bilbao Rosé",
      "Ramón Bilbao (Rioja)",
      "Ramón Bilbao rosato (Rioja)",
      "Ramón Bilbao (Rioja)",
    ),
    L("Fresco.", "Fresh.", "Frais.", "Frisch.", "Fresc.", "Fresco.", "Fresco."),
    4,
    undefined,
    L("4 / 18 €", "€4 / €18", "4 / 18 €", "4 / 18 €", "4 / 18 €", "4 / 18 €", "4 / 18 €"),
  ),

  dish(
    "vin-vermu",
    cat.vermu,
    L(
      "Vermú (rojo / blanco / rosado / mixto)",
      "Vermouth (red / white / rosé / mixed)",
      "Vermouth rouge, blanc, rosé, mixte",
      "Wermut rot, weiß, rosé, mix",
      "Vermut (tint / blanc / rosat / mixt)",
      "Vermouth (rosso / bianco / rosato / misto)",
      "Vermute (tinto / branco / rosado / misto)",
    ),
    L("Copa.", "Glass.", "Verre.", "Glas.", "Copa.", "Calice.", "Copo."),
    4,
  ),

  dish(
    "vin-cava",
    cat.cavas,
    L("Cava brut nature", "Brut nature cava", "Cava brut nature", "Cava brut nature", "Cava brut nature", "Cava brut nature", "Cava brut nature"),
    L(
      "Copa / botella.",
      "Glass / bottle.",
      "Verre / bouteille.",
      "Glas / Flasche.",
      "Copa / ampolla.",
      "Calice / bottiglia.",
      "Copo / garrafa.",
    ),
    4,
    undefined,
    L("4 / 24 €", "€4 / €24", "4 / 24 €", "4 / 24 €", "4 / 24 €", "4 / 24 €", "4 / 24 €"),
  ),
];
